/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author arwel
 */
public class MainBayesFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainBayesFrams
     */
    public MainBayesFrame() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bayesRunButton = new javax.swing.JButton();
        bayesStopButton = new javax.swing.JButton();
        bayesProgressBar = new javax.swing.JProgressBar();
        bayesExitButton = new javax.swing.JButton();
        bayesSaveButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        fitAndALDPanel = new javax.swing.JPanel();
        posteriorsPanel = new javax.swing.JPanel();
        diagnosticsPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();

        setFocusable(false);

        bayesRunButton.setText("Run");

        bayesStopButton.setText("Stop");

        bayesProgressBar.setMinimum(10);
        bayesProgressBar.setMinimumSize(new java.awt.Dimension(100, 20));

        bayesExitButton.setText("Exit");

        bayesSaveButton.setText("Save");

        javax.swing.GroupLayout fitAndALDPanelLayout = new javax.swing.GroupLayout(fitAndALDPanel);
        fitAndALDPanel.setLayout(fitAndALDPanelLayout);
        fitAndALDPanelLayout.setHorizontalGroup(
            fitAndALDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
        );
        fitAndALDPanelLayout.setVerticalGroup(
            fitAndALDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Fits and SLD", fitAndALDPanel);

        javax.swing.GroupLayout posteriorsPanelLayout = new javax.swing.GroupLayout(posteriorsPanel);
        posteriorsPanel.setLayout(posteriorsPanelLayout);
        posteriorsPanelLayout.setHorizontalGroup(
            posteriorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
        );
        posteriorsPanelLayout.setVerticalGroup(
            posteriorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Posteriors", posteriorsPanel);
        posteriorsPanel.getAccessibleContext().setAccessibleName("Posteriors");

        javax.swing.GroupLayout diagnosticsPanelLayout = new javax.swing.GroupLayout(diagnosticsPanel);
        diagnosticsPanel.setLayout(diagnosticsPanelLayout);
        diagnosticsPanelLayout.setHorizontalGroup(
            diagnosticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
        );
        diagnosticsPanelLayout.setVerticalGroup(
            diagnosticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Diagnostics", diagnosticsPanel);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Main Panel", mainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bayesRunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bayesStopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bayesSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bayesProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(283, 283, 283)
                        .addComponent(bayesExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bayesExitButton)
                    .addComponent(bayesProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bayesRunButton)
                        .addComponent(bayesStopButton)
                        .addComponent(bayesSaveButton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainBayesFrame().setVisible(true);
            }
        });
    }
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bayesExitButton;
    private javax.swing.JProgressBar bayesProgressBar;
    private javax.swing.JButton bayesRunButton;
    private javax.swing.JButton bayesSaveButton;
    private javax.swing.JButton bayesStopButton;
    private javax.swing.JPanel diagnosticsPanel;
    private javax.swing.JPanel fitAndALDPanel;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel posteriorsPanel;
    // End of variables declaration//GEN-END:variables
}
