
import java.awt.CardLayout;
import javax.swing.JComboBox;


//import javax.swing.JComboBox;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author arwel
 */



public class MainPanelContainer extends javax.swing.JPanel {

    /**
     * Creates new form MainPanelContainer
     */
    public MainPanelContainer() {
        initComponents();
    }

    public javax.swing.JComboBox getBayesTypeComboBox() {
        return bayesAnalysisTypeComboBox;
    };
    
    public javax.swing.JPanel getBayesSettingsPanel() {
        return bayesSettingsPanel;
    }
    
    public javax.swing.JTextArea getBayesTextArea() {
        return bayesTextArea;
    }
    
    public javax.swing.JScrollPane getBayesParamsScrollpane() {
        return bayesParamsScrollpane;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bayesAnalysisTypeComboBox = new javax.swing.JComboBox<>();
        bayesSettingsPanel = new javax.swing.JPanel();
        bayesParamsScrollpane = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        bayesTextArea = new javax.swing.JTextArea();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Analysis Type");

        bayesAnalysisTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Parameter Estimation", "Model Selection" }));
        bayesAnalysisTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayesAnalysisTypeComboBoxActionPerformed(evt);
            }
        });

        bayesSettingsPanel.setBackground(java.awt.Color.white);
        bayesSettingsPanel.setOpaque(false);
        bayesSettingsPanel.setLayout(new java.awt.CardLayout());

        bayesTextArea.setEditable(false);
        bayesTextArea.setColumns(20);
        bayesTextArea.setRows(5);
        bayesTextArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(bayesTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(bayesSettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bayesParamsScrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bayesAnalysisTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bayesAnalysisTypeComboBox)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bayesParamsScrollpane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bayesSettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void bayesAnalysisTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayesAnalysisTypeComboBoxActionPerformed
      /**CardLayout card = (CardLayout)bayesSettingsPanel.getLayout(); 
      JComboBox box = (JComboBox)evt.getSource();
      String which = (String)box.getSelectedItem();
      switch (which) {
          case "Parameter Estimation" :
              card.show(bayesSettingsPanel,"mcmcStatCardLayoutPanel");
              System.out.println("Debug pEst");
          case "Model Selection" :
              card.show(bayesSettingsPanel, "nestedSamplerCardLayoutPanel");
          default:
              card.show(bayesSettingsPanel,"mcmcStatCardLayoutPanel");
      } 
      bayesSettingsPanel.repaint(); */
                                        
      CardLayout card = (CardLayout)bayesSettingsPanel.getLayout();
      JComboBox<String> box = (JComboBox<String>)evt.getSource();
      String which = (String)box.getSelectedItem();
      
      if(which.equals("Parameter Estimation")) {
            card.show(mainPanel, "PanelOne");
      } else if (which.equals("Panel Two")) {
            card.show(mainPanel, "PanelTwo");
      }
      
      
      
      
      
      
      
      
    }//GEN-LAST:event_bayesAnalysisTypeComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bayesAnalysisTypeComboBox;
    private javax.swing.JScrollPane bayesParamsScrollpane;
    private javax.swing.JPanel bayesSettingsPanel;
    private javax.swing.JTextArea bayesTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
