/*
 * bootstrapPanel.java
 *
 * Created on 23 January 2009, 15:36
 */
import java.io.Serializable;
/**
 *
 * @author  avh45
 */
public class bootstrapPanel extends javax.swing.JPanel implements Serializable {
    
    public int interrupt;
    
    /** Creates new form bootstrapPanel */
    public bootstrapPanel() {
        initComponents();
    }
    
    public javax.swing.JPanel getBsSLDPanel() {
        return bootStrapSLDPanel;
    }
    
    public javax.swing.JPanel getBsBarPanel() {
        return bootStrapBarPanel;
    }
    
    public javax.swing.JScrollPane getBsTableScrollPane() {
        return jScrollPane1;
    }
    
    public javax.swing.JButton getBsStartButton() {
        return bootStrapStartButton;
    }
    
    public javax.swing.JTextField getBsNRunsBox() {
        return bootStrapNRunsBox;
    }
    
    public javax.swing.JProgressBar getBsProgressBar() {
        return BsProgressBar;
    }

    public javax.swing.JComboBox getWhichParamCombo() {
        return whichParamCombo;
    }
    
    public void setInterruptFlag(int Value) {
        interrupt = Value;
    }
    
    public int getInterruptFlag() {
        return interrupt;
    }
    
    public javax.swing.JComboBox getbootStrapAlgComboBox() {
        return bootStrapAlgComboBox;
    }
    
    public javax.swing.JCheckBox getUseRandomBox() {
        return useRandomCBox;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        bootStrapAbortButton = new javax.swing.JButton();
        bootStrapStartButton = new javax.swing.JButton();
        bootStrapBarPanel = new javax.swing.JPanel();
        bootStrapSLDPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bootStrapAlgComboBox = new javax.swing.JComboBox();
        bootStrapNRunsBox = new javax.swing.JTextField();
        BsProgressBar = new javax.swing.JProgressBar();
        whichParamCombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        useRandomCBox = new javax.swing.JCheckBox();

        bootStrapAbortButton.setText("Abort");
        bootStrapAbortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bootStrapAbortButtonActionPerformed(evt);
            }
        });

        bootStrapStartButton.setText("Start");

        bootStrapBarPanel.setLayout(new java.awt.BorderLayout());

        bootStrapBarPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bootStrapSLDPanel.setLayout(new java.awt.BorderLayout());

        bootStrapSLDPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Algorithm");

        jLabel2.setText("Numberof runs");

        bootStrapAlgComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simplex", "Genetic" }));

        bootStrapNRunsBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bootStrapNRunsBox.setText("100");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("View Parameter :");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Status : ");

        useRandomCBox.setSelected(true);
        useRandomCBox.setText("Use random parameter starting values");
        useRandomCBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        useRandomCBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(bootStrapSLDPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(whichParamCombo, 0, 157, Short.MAX_VALUE))
                            .add(bootStrapBarPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel2)
                            .add(jLabel1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, bootStrapAlgComboBox, 0, 122, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, bootStrapNRunsBox, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 50, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(BsProgressBar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(bootStrapStartButton)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(bootStrapAbortButton))))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, useRandomCBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 256, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(bootStrapAbortButton)
                            .add(bootStrapStartButton))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(BsProgressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(bootStrapAlgComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(bootStrapNRunsBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel4))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(bootStrapBarPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(whichParamCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel3)))
                    .add(bootStrapSLDPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(useRandomCBox)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bootStrapAbortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bootStrapAbortButtonActionPerformed
        setInterruptFlag(1);
    }//GEN-LAST:event_bootStrapAbortButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BsProgressBar;
    private javax.swing.JButton bootStrapAbortButton;
    private javax.swing.JComboBox bootStrapAlgComboBox;
    private javax.swing.JPanel bootStrapBarPanel;
    private javax.swing.JTextField bootStrapNRunsBox;
    private javax.swing.JPanel bootStrapSLDPanel;
    private javax.swing.JButton bootStrapStartButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox useRandomCBox;
    private javax.swing.JComboBox whichParamCombo;
    // End of variables declaration//GEN-END:variables
    
}
