/*
 * DEOptionsPanel.java
 *
 * Created on 15 February 2010, 10:39
 */

/**
 *
 * @author  avh45
 */
public class DEOptionsPanel extends javax.swing.JPanel {
    
    /** Creates new form DEOptionsPanel */
    public DEOptionsPanel() {
        initComponents();
    }

    public javax.swing.JTextField getCRprobTextField() {
        return CRprobTextField;
    }

    public javax.swing.JTextField getVTRTextfield() {
        return VTRTextfield;
    }

    public javax.swing.JTextField getPopSizeTextField() {
        return popSizeTextField;
    }

    public javax.swing.JTextField getStepSizeTextField() {
        return stepSizeTextField;
    }

    public javax.swing.JComboBox getStrategyComboBox() {
        return strategyComboBox;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        VTRTextfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        popSizeTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        stepSizeTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CRprobTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        strategyComboBox = new javax.swing.JComboBox();

        jLabel1.setText("Value to reach");

        VTRTextfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        VTRTextfield.setText("1");

        jLabel2.setText("Population SIze");

        popSizeTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        popSizeTextField.setText("50");

        jLabel3.setText("DE Step Size (0 - 2)");

        stepSizeTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stepSizeTextField.setText("0.8");

        jLabel4.setText("Crossover Probability (0 - 1)");

        CRprobTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CRprobTextField.setText("0.8");

        jLabel5.setText("Strategy");

        strategyComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DE/best/1/exp", "DE/rand/1/exp", "DE/rand-to-best/1/exp", "DE/rand/2/exp", "DE/best/1/bin", "DE/rand/1/bin", "DE/rand-to-best/1/bin", "DE/best/2/bin", "DE/rand/2/bin" }));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(popSizeTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .add(VTRTextfield, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .add(stepSizeTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .add(CRprobTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .add(strategyComboBox, 0, 236, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(VTRTextfield, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(popSizeTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(stepSizeTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(CRprobTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(strategyComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CRprobTextField;
    private javax.swing.JTextField VTRTextfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField popSizeTextField;
    private javax.swing.JTextField stepSizeTextField;
    private javax.swing.JComboBox strategyComboBox;
    // End of variables declaration//GEN-END:variables
    
}
