/*
 * errorStatsPanel.java
 *
 * Created on 23 January 2009, 09:52
 */
import java.io.Serializable;
/**
 *
 * @author  avh45
 */
public class errorStatsPanel extends javax.swing.JPanel implements Serializable {
    
    /** Creates new form errorStatsPanel */
    public errorStatsPanel() {
        initComponents();
    }
    
    public javax.swing.JScrollPane getHessScrollPane() {
        return hessScrollPane;
    }
    
    public javax.swing.JScrollPane getCovScrollPane() {
        return covScrollPane;
    } 
    
    public javax.swing.JScrollPane getCorrScrollPane() {
        return corrScrollPane;
    }
    
    public javax.swing.JScrollPane getErrScrollPane() {
        return stdErrorScrollPane;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        covScrollPane = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        corrScrollPane = new javax.swing.JScrollPane();
        jLabel3 = new javax.swing.JLabel();
        hessScrollPane = new javax.swing.JScrollPane();
        jLabel4 = new javax.swing.JLabel();
        stdErrorScrollPane = new javax.swing.JScrollPane();

        jLabel1.setText("Standard Error");

        jLabel2.setText("Covariance Matrix");

        jLabel3.setText("Correlation Matrix");

        jLabel4.setText("Hessian");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, hessScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, stdErrorScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel2)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel3)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, covScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, corrScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(stdErrorScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(30, 30, 30)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(covScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(30, 30, 30)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(corrScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(30, 30, 30)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(hessScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane corrScrollPane;
    private javax.swing.JScrollPane covScrollPane;
    private javax.swing.JScrollPane hessScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane stdErrorScrollPane;
    // End of variables declaration//GEN-END:variables
    
}
