/*
 * fittingOptionsFrame.java
 *
 * Created on 12 August 2008, 12:31
 */
import java.awt.Container;
import javax.swing.JComponent;
import org.jdesktop.jxlayer.JXLayer;
import org.jdesktop.jxlayer.plaf.ext.LockableUI;
import org.jdesktop.jxlayer.plaf.effect.BufferedImageOpEffect;
//import com.jhlabs.image.BlurFilter;
import java.io.Serializable;

/**
 *
 * @author  avh45
 */
public class fittingOptionsFrame extends javax.swing.JInternalFrame implements Serializable {
    
    private JXLayer<JComponent> layer;
    private LockableUI blurUI = new LockableUI();
    
    
    /** Creates new form fittingOptionsFrame */
    public fittingOptionsFrame() {
        initComponents();
        JComponent view = (JComponent) this.getContentPane();  
        layer = new JXLayer(view, blurUI);
        blurUI.setLocked(false);
        layer.setUI(blurUI);
        this.setContentPane((layer));
    }



    public javax.swing.JButton getFitOptionsCancelButton() {
        return fitOptionsCancelButton;
    }

    public javax.swing.JButton getFitOptionsOkButton() {
        return fitOptionsOkButton;
    }


    public javax.swing.JTabbedPane getAlgOptionsTabbedPane() {
        return algOptionsTabbedPane;
    }

    
    public void setLocked() {
        blurUI.setLocked(true);
        repaint();
    }

    public void setUnlocked() {
        blurUI.setLocked(false);
        repaint();
    }

   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel2 = new javax.swing.JLabel();
        fitOptionsCancelButton = new javax.swing.JButton();
        fitOptionsOkButton = new javax.swing.JButton();
        algOptionsTabbedPane = new javax.swing.JTabbedPane();

        jLabel2.setText("jLabel2");

        setTitle("Preferences");

        fitOptionsCancelButton.setText("Cancel");

        fitOptionsOkButton.setText("OK");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, algOptionsTabbedPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(fitOptionsOkButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(fitOptionsCancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(algOptionsTabbedPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(fitOptionsOkButton)
                    .add(fitOptionsCancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane algOptionsTabbedPane;
    private javax.swing.JButton fitOptionsCancelButton;
    private javax.swing.JButton fitOptionsOkButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    
}
