/*
 * mainGuiExpDetails.java
 *
 * Created on 28 April 2008, 15:05
 */
import java.io.Serializable;
/**
 *
 * @author  avh45
 */
public class mainGuiExpDetails extends javax.swing.JPanel implements Serializable{
    
    /** Creates new form mainGuiExpDetails */
    public mainGuiExpDetails() {
        initComponents();
    }

    public javax.swing.JScrollPane getJScrollPane1() {
        return jScrollPane1;
    }

    public mainGuiExpDetailsPanel getMainGuiExpDetailsPanel1() {
        return mainGuiExpDetailsPanel1;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        mainGuiExpDetailsPanel1 = new mainGuiExpDetailsPanel();

        jScrollPane1.setViewportView(mainGuiExpDetailsPanel1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private mainGuiExpDetailsPanel mainGuiExpDetailsPanel1;
    // End of variables declaration//GEN-END:variables
    
}
