/*
 * mainGuiExpDetailsPanel.java
 *
 * Created on 28 April 2008, 14:58
 */
import java.io.Serializable;
/**
 *
 * @author  avh45
 */
public class mainGuiExpDetailsPanel extends javax.swing.JPanel implements Serializable{
    
    /** Creates new form mainGuiExpDetailsPanel */
    public mainGuiExpDetailsPanel() {
        initComponents();
    }

    public javax.swing.JScrollPane getBackScrPane() {
        return backScrPane;
    }

    public javax.swing.JScrollPane getNbInScrPane() {
        return nbInScrPane;
    }

    public javax.swing.JScrollPane getNbOutScrPane() {
        return nbOutScrPane;
    }

    public javax.swing.JScrollPane getScalefacScrPane() {
        return scalefacScrPane;
    }

    public javax.swing.JScrollPane getShiftScrPane() {
        return shiftScrPane;
    }

    public javax.swing.JScrollPane getResolutionScrollPane() {
        return resolutionScrollPane;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        backScrPane = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        scalefacScrPane = new javax.swing.JScrollPane();
        jLabel3 = new javax.swing.JLabel();
        shiftScrPane = new javax.swing.JScrollPane();
        jLabel4 = new javax.swing.JLabel();
        nbInScrPane = new javax.swing.JScrollPane();
        jLabel5 = new javax.swing.JLabel();
        nbOutScrPane = new javax.swing.JScrollPane();
        jLabel6 = new javax.swing.JLabel();
        resolutionScrollPane = new javax.swing.JScrollPane();

        jLabel1.setText("Backgrounds");

        jLabel2.setText("Scale Factors");

        jLabel3.setText("Qz Shifts");

        jLabel4.setText("Bulk In SLD's");

        jLabel5.setText("Bulk Out SLD's");

        jLabel6.setText("Resolution");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .add(backScrPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .add(scalefacScrPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .add(shiftScrPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .add(nbInScrPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .add(nbOutScrPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .add(resolutionScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(backScrPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(scalefacScrPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(shiftScrPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(nbInScrPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(nbOutScrPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(resolutionScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane backScrPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane nbInScrPane;
    private javax.swing.JScrollPane nbOutScrPane;
    private javax.swing.JScrollPane resolutionScrollPane;
    private javax.swing.JScrollPane scalefacScrPane;
    private javax.swing.JScrollPane shiftScrPane;
    // End of variables declaration//GEN-END:variables
    
}
