/*
 * mainGuiContrastPanel.java
 *
 * Created on 02 May 2008, 13:46
 */
import java.io.Serializable;
/**
 *
 * @author  avh45
 */
public class mainGuiContrastPanel extends javax.swing.JPanel implements Serializable{
    
    /** Creates new form mainGuiContrastPanel */
    public mainGuiContrastPanel() {
        initComponents();
    }

    public javax.swing.JTextField getMainGuiContrastBackTxtFld() {
        return mainGuiContrastBackTxtFld;
    }

    public javax.swing.JCheckBox getMainGuiResampleCheckbox() {
        return useResamplingCheckBox;
    }
    
    public javax.swing.JTextField getMainGuiContrastNameTxtFld() {
        return mainGuiContrastNameTxtFld;
    }

    public javax.swing.JTextField getMainGuiContrastPathTxtFld() {
        return mainGuiContrastPathTxtFld;
    }

    public javax.swing.JTextField getMainGuiContrastScalefTxtFld() {
        return mainGuiContrastScalefTxtFld;
    }

    public javax.swing.JScrollPane getMainGuiContrastScrollPane() {
        return mainGuiContrastScrollPane;
    }

    public javax.swing.JTextField getMainGuiContrastShiftTxtFld() {
        return mainGuiContrastShiftTxtFld;
    }

    public javax.swing.JTextField getMainGuiContrastTypeTxtFld() {
        return mainGuiContrastTypeTxtFld;
    }

    public javax.swing.JTextField getDataQmaxTextField() {
        return dataQmaxTextField;
    }

    public javax.swing.JTextField getDataQminTextField() {
        return dataQminTextField;
    }

    public javax.swing.JTextField getSimQmaxTextField() {
        return simQmaxTextField;
    }

    public javax.swing.JTextField getSimQminTextField() {
        return simQminTextField;
    }

    public javax.swing.JCheckBox getRepeatLayersCheckbox() {
        return repeatLayersCheckbox;
    }

    public javax.swing.JTextField getRepeatLayersTextBox() {
        return repeatLayersTextBox;
    }

    public javax.swing.JLabel getSimNPointsLabel() {
        return simNPointsLabel;
    }

    public javax.swing.JTextField getSimNPointsTextBox() {
        return simNPointsTextBox;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mainGuiContrastNameTxtFld = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mainGuiContrastTypeTxtFld = new javax.swing.JTextField();
        mainGuiContrastPathTxtFld = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mainGuiContrastBackTxtFld = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mainGuiContrastScalefTxtFld = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mainGuiContrastShiftTxtFld = new javax.swing.JTextField();
        mainGuiContrastScrollPane = new javax.swing.JScrollPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dataQminTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dataQmaxTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        simQminTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        simQmaxTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        repeatLayersCheckbox = new javax.swing.JCheckBox();
        repeatLayersTextBox = new javax.swing.JTextField();
        simNPointsTextBox = new javax.swing.JTextField();
        simNPointsLabel = new javax.swing.JLabel();
        useResamplingCheckBox = new javax.swing.JCheckBox();

        jLabel1.setText("Contrast Name :");

        mainGuiContrastNameTxtFld.setEditable(false);

        jLabel2.setText("Type :");

        mainGuiContrastTypeTxtFld.setEditable(false);
        mainGuiContrastTypeTxtFld.setMinimumSize(new java.awt.Dimension(20, 20));

        mainGuiContrastPathTxtFld.setEditable(false);

        jLabel3.setText("Background :");

        mainGuiContrastBackTxtFld.setEditable(false);
        mainGuiContrastBackTxtFld.setMinimumSize(new java.awt.Dimension(6, 10));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Scalefac :");

        mainGuiContrastScalefTxtFld.setEditable(false);
        mainGuiContrastScalefTxtFld.setMinimumSize(new java.awt.Dimension(6, 10));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Shift :");

        mainGuiContrastShiftTxtFld.setEditable(false);
        mainGuiContrastShiftTxtFld.setMinimumSize(new java.awt.Dimension(6, 10));

        jLabel6.setText("Data Range : ");

        jLabel7.setText("Qmin :");

        jLabel8.setText("Qmax :");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Qmin :");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Qmax :");

        jLabel11.setText("Sim range :");

        repeatLayersCheckbox.setText("Repeat Layers   x");
        repeatLayersCheckbox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        repeatLayersTextBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        repeatLayersTextBox.setText("1");

        simNPointsTextBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        simNPointsTextBox.setText("100");

        simNPointsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simNPointsLabel.setText("sim nPoints");

        useResamplingCheckBox.setText("Use Resampling");
        useResamplingCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useResamplingCheckBoxActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, mainGuiContrastScrollPane)
                    .add(layout.createSequentialGroup()
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel6)
                            .add(layout.createSequentialGroup()
                                .add(dataQminTextField)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel8)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(dataQmaxTextField)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(simQminTextField)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(simQmaxTextField))
                            .add(jLabel11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(mainGuiContrastBackTxtFld, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(layout.createSequentialGroup()
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(mainGuiContrastTypeTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(mainGuiContrastPathTxtFld)
                                    .add(layout.createSequentialGroup()
                                        .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(18, 18, 18)
                                        .add(mainGuiContrastScalefTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 121, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                        .add(135, 135, 135))))
                            .add(mainGuiContrastNameTxtFld)))
                    .add(layout.createSequentialGroup()
                        .add(repeatLayersCheckbox)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(repeatLayersTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(useResamplingCheckBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 169, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(simNPointsLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(simNPointsTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 135, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(mainGuiContrastShiftTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 135, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(mainGuiContrastNameTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(mainGuiContrastTypeTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(mainGuiContrastPathTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(mainGuiContrastBackTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4)
                    .add(mainGuiContrastScalefTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5)
                    .add(mainGuiContrastShiftTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(repeatLayersCheckbox)
                        .add(repeatLayersTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(useResamplingCheckBox)
                        .add(simNPointsLabel)
                        .add(simNPointsTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(mainGuiContrastScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(jLabel6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(jLabel8)
                    .add(dataQmaxTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(dataQminTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9)
                    .add(simQmaxTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel10)
                    .add(simQminTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void useResamplingCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useResamplingCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useResamplingCheckBoxActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dataQmaxTextField;
    private javax.swing.JTextField dataQminTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mainGuiContrastBackTxtFld;
    private javax.swing.JTextField mainGuiContrastNameTxtFld;
    private javax.swing.JTextField mainGuiContrastPathTxtFld;
    private javax.swing.JTextField mainGuiContrastScalefTxtFld;
    private javax.swing.JScrollPane mainGuiContrastScrollPane;
    private javax.swing.JTextField mainGuiContrastShiftTxtFld;
    private javax.swing.JTextField mainGuiContrastTypeTxtFld;
    private javax.swing.JCheckBox repeatLayersCheckbox;
    private javax.swing.JTextField repeatLayersTextBox;
    private javax.swing.JLabel simNPointsLabel;
    private javax.swing.JTextField simNPointsTextBox;
    private javax.swing.JTextField simQmaxTextField;
    private javax.swing.JTextField simQminTextField;
    private javax.swing.JCheckBox useResamplingCheckBox;
    // End of variables declaration//GEN-END:variables
    
}
