/*
 * simplexOptionsPanel.java
 *
 * Created on 24 October 2008, 13:25
 */
import java.io.Serializable;
/**
 *
 * @author  avh45
 */
public class simplexOptionsPanel extends javax.swing.JPanel implements Serializable {
    
    /** Creates new form simplexOptionsPanel */
    public simplexOptionsPanel() {
        initComponents();
    }

    public javax.swing.JTextField getSmplxFunTolBox() {
        return smplxFunTolBox;
    }

    public javax.swing.JTextField getSmplxMaxFunEvalsBox() {
        return smplxMaxFunEvalsBox;
    }

    public javax.swing.JTextField getSmplxStopParamTol() {
        return smplxStopParamTol;
    }

    public javax.swing.JTextField getSmplxTargetChiBox() {
        return smplxTargetChiBox;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        smplxTargetChiBox = new javax.swing.JTextField();
        smplxMaxFunEvalsBox = new javax.swing.JTextField();
        smplxStopParamTol = new javax.swing.JTextField();
        smplxFunTolBox = new javax.swing.JTextField();

        jLabel1.setText("Target Chi Squared");

        jLabel2.setText("Maximum Function Evals");

        jLabel3.setText("Stop Param Tolerance");

        jLabel4.setText("Stop Function Tolerance");

        smplxTargetChiBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        smplxTargetChiBox.setText("1");

        smplxMaxFunEvalsBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        smplxMaxFunEvalsBox.setText("1e10");

        smplxStopParamTol.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        smplxStopParamTol.setText("1e-8");

        smplxFunTolBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        smplxFunTolBox.setText("1e-8");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(smplxTargetChiBox, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .add(smplxStopParamTol, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .add(smplxMaxFunEvalsBox, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .add(smplxFunTolBox, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(smplxTargetChiBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(smplxMaxFunEvalsBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(smplxStopParamTol, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(smplxFunTolBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField smplxFunTolBox;
    private javax.swing.JTextField smplxMaxFunEvalsBox;
    private javax.swing.JTextField smplxStopParamTol;
    private javax.swing.JTextField smplxTargetChiBox;
    // End of variables declaration//GEN-END:variables
    
}
