/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author arwelhughes
 */
public class MainBayesPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public MainBayesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        algComboBox = new javax.swing.JComboBox<>();
        mainTableScrollPane = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        mcmcPointsBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        burnInTextBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        repeatRunsTextBox = new javax.swing.JTextField();
        startButton = new javax.swing.JButton();
        abortButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bayesTextField = new javax.swing.JTextArea();
        exportButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        continueButton = new javax.swing.JButton();

        jLabel1.setText("Analysis Type");

        algComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Parameter Est (MCMC)", "Model Selection (NS)" }));
        algComboBox.setEnabled(false);
        algComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algComboBoxActionPerformed(evt);
            }
        });

        mainTableScrollPane.setMaximumSize(new java.awt.Dimension(132767, 32767));

        jLabel2.setText("MCMC points");

        mcmcPointsBox.setText("10000");
        mcmcPointsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcmcPointsBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Burn-in points");

        burnInTextBox.setText("1000");

        jLabel4.setText("Repeat Runs");

        repeatRunsTextBox.setText("3");
        repeatRunsTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repeatRunsTextBoxActionPerformed(evt);
            }
        });

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        abortButton.setText("Abort");

        bayesTextField.setEditable(false);
        bayesTextField.setColumns(20);
        bayesTextField.setRows(5);
        jScrollPane1.setViewportView(bayesTextField);

        exportButton.setText("Export");
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        quitButton.setText("Quit");

        continueButton.setText("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(algComboBox, 0, 272, Short.MAX_VALUE)
                            .addComponent(mcmcPointsBox)
                            .addComponent(burnInTextBox)
                            .addComponent(repeatRunsTextBox)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abortButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exportButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(continueButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quitButton)))
                .addGap(18, 18, 18)
                .addComponent(mainTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(algComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(mcmcPointsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(burnInTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(repeatRunsTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(abortButton)
                            .addComponent(startButton)
                            .addComponent(exportButton)
                            .addComponent(quitButton)
                            .addComponent(continueButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                    .addComponent(mainTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void algComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_algComboBoxActionPerformed

    private void mcmcPointsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcmcPointsBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mcmcPointsBoxActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startButtonActionPerformed

    private void repeatRunsTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repeatRunsTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repeatRunsTextBoxActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportButtonActionPerformed

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continueButtonActionPerformed

    public javax.swing.JComboBox getAlgComboBox() {
        return algComboBox;
    }
            
    public javax.swing.JTextField getMcmcPointsBox() {
        return mcmcPointsBox;
    }
    
    public javax.swing.JTextField getBurninTextBox() {
        return burnInTextBox;
    }
   
    public javax.swing.JTextField getRepeatRunsTextBox() {
        return repeatRunsTextBox;
    }
    
    public javax.swing.JButton getStartButton() {
        return startButton;
    }
      
    public javax.swing.JButton getAbortButton() {
        return abortButton;
    }
    
    public javax.swing.JButton getExportButton() {
        return exportButton;
    }
    
    public javax.swing.JButton getQuitButton() {
        return quitButton;
    }
    
    public javax.swing.JButton getContinueButton() {
        return continueButton;
    }
    
    public javax.swing.JScrollPane getMainTableScrollPane() {
        return mainTableScrollPane;
    }

    public javax.swing.JTextArea getBayesTextArea() {
        return bayesTextField;
    }
    

            
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abortButton;
    private javax.swing.JComboBox<String> algComboBox;
    private javax.swing.JTextArea bayesTextField;
    private javax.swing.JTextField burnInTextBox;
    private javax.swing.JButton continueButton;
    private javax.swing.JButton exportButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane mainTableScrollPane;
    private javax.swing.JTextField mcmcPointsBox;
    private javax.swing.JButton quitButton;
    private javax.swing.JTextField repeatRunsTextBox;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
