/*
 * contrastGui.java
 *
 * Created on 08 January 2008, 11:15
 */

/**
 *
 * @author  avh45
 */
public class contrastGui extends javax.swing.JPanel {
    
    /** Creates new form contrastGui */
    public contrastGui() {
        initComponents();
    }
    
    public javax.swing.JComboBox getTypeComboBox() {
        return typeComboBox;
    }
    
    public void hideFileItems() {
        //getFileNameBrowseButton().setVisible(false);
        getOgEditButton().setVisible(false);
        //fileNameLabel.setVisible(false);
        //fileNameTextField.setVisible(false);
        //fileTypeComboBox.setVisible(false);
        //fileTypeLabel.setVisible(false);
        filePanel.setVisible(false);
    }
    
    public void showOpenGenieItems() {
        getOgEditButton().setVisible(true);
        //getFileNameBrowseButton().setVisible(false);
        //fileNameLabel.setVisible(false);
        //fileNameTextField.setVisible(false);
        //fileTypeComboBox.setVisible(false);
        //fileTypeLabel.setVisible(false);
        filePanel.setVisible(false);
    }
    
    public void showFileItems() {
        //getFileNameBrowseButton().setVisible(true);
        //getOgEditButton().setVisible(false);
        //fileNameLabel.setVisible(true);
        //fileNameTextField.setVisible(true);
        //fileTypeLabel.setVisible(true);
        filePanel.setVisible(true);
    }
    
    public void enableLayersItems() {
        numberOfLaysTextBox.setEnabled(true);
        addLayersButton.setEnabled(true);
        removeLayers.setEnabled(true);
    }
    
    public void disableLayersItems() {
        numberOfLaysTextBox.setEnabled(false);
        addLayersButton.setEnabled(false);
        removeLayers.setEnabled(false);
    }    
    
    public javax.swing.JTextField getFileTextField() {
        return fileNameTextField;
    }
    
    public javax.swing.JComboBox getBackgroundComboBox() {
        return backgroundComboBox;
    }
    
    public javax.swing.JComboBox getScalefacComboBox() {
        return scalefacComboBox;
    }    
    
    public javax.swing.JComboBox getShiftComboBox() {
        return shiftsComboBox;
    }
    
    public javax.swing.JScrollPane getLayersDetailsScrollPane() {
        return layersDetailsScrollPane;
    }
    
    public javax.swing.JTextField getNumberOfLaysTextBox() {
        return numberOfLaysTextBox;
    }
    
    public javax.swing.JButton getAddLayersButton() {
        return addLayersButton;
    }
    
    public javax.swing.JButton getRemoveLayersButton() {
        return removeLayers;
    }    
    
    public javax.swing.JTextField getContrastNameTextField() {
        return contrastNameTextField;
    }

    public javax.swing.JButton getFileNameBrowseButton() {
        return fileNameBrowseButton;
    }

    public javax.swing.JButton getOgEditButton() {
        return ogEditButton;
    }

    public javax.swing.JComboBox getResolComboBox() {
        return resolComboBox;
    }
    
    public javax.swing.JComboBox getFileTypeComboBox() {
        return fileTypeComboBox;
    }

    public javax.swing.JRadioButton getReloadFileButtonGroup() {
        return ReloadFileButtonGroup;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        layersDetailsScrollPane = new javax.swing.JScrollPane();
        contrastNameTextField = new javax.swing.JTextField();
        filePanel = new javax.swing.JPanel();
        fileNameBrowseButton = new javax.swing.JButton();
        fileNameLabel = new javax.swing.JLabel();
        fileTypeComboBox = new javax.swing.JComboBox();
        fileNameTextField = new javax.swing.JTextField();
        fileTypeLabel = new javax.swing.JLabel();
        ReloadFileButtonGroup = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addLayersButton = new javax.swing.JButton();
        numberOfLaysTextBox = new javax.swing.JTextField();
        backgroundComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        resolComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        removeLayers = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        shiftsComboBox = new javax.swing.JComboBox();
        scalefacComboBox = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        typeComboBox = new javax.swing.JComboBox();
        ogEditButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        contrastNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        fileNameBrowseButton.setText("Browse");

        fileNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fileNameLabel.setText("File");

        fileTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3 column ascii, no header.", "3 column ascii, single line header.", "ISIS histogram (.asc)", " " }));
        fileTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileTypeComboBoxActionPerformed(evt);
            }
        });

        fileNameTextField.setEditable(false);
        fileNameTextField.setText("c:\\myFile");

        fileTypeLabel.setText("Type");

        ReloadFileButtonGroup.setText(" Reload file even if local copy present in data directory");
        ReloadFileButtonGroup.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ReloadFileButtonGroup.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ReloadFileButtonGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReloadFileButtonGroupActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout filePanelLayout = new org.jdesktop.layout.GroupLayout(filePanel);
        filePanel.setLayout(filePanelLayout);
        filePanelLayout.setHorizontalGroup(
            filePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(filePanelLayout.createSequentialGroup()
                .add(filePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(fileNameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(filePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(fileTypeLabel)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(filePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(filePanelLayout.createSequentialGroup()
                        .add(fileTypeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 229, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(ReloadFileButtonGroup, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
                    .add(filePanelLayout.createSequentialGroup()
                        .add(fileNameTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(fileNameBrowseButton)))
                .addContainerGap())
        );
        filePanelLayout.setVerticalGroup(
            filePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(filePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(filePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(fileNameLabel)
                    .add(fileNameBrowseButton)
                    .add(fileNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(15, 15, 15)
                .add(filePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(fileTypeLabel)
                    .add(fileTypeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ReloadFileButtonGroup))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Resolution");

        addLayersButton.setText("Add");

        numberOfLaysTextBox.setEditable(false);
        numberOfLaysTextBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numberOfLaysTextBox.setText("3");

        backgroundComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Background 1" }));

        jLabel4.setText("Scalefactor");

        resolComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Background");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Number of Layers");

        removeLayers.setText("Remove");

        jLabel5.setText("Qz shift");

        shiftsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(numberOfLaysTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(addLayersButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(removeLayers))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, scalefacComboBox, 0, 112, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, shiftsComboBox, 0, 112, Short.MAX_VALUE)
                            .add(resolComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(backgroundComboBox, 0, 144, Short.MAX_VALUE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(backgroundComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(scalefacComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(shiftsComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(resolComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 129, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(numberOfLaysTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(removeLayers)
                    .add(addLayersButton))
                .addContainerGap())
        );

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simulation", "Ascii File", "OpenGenie Script" }));

        ogEditButton.setText("Edit");

        jLabel1.setText("Type");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(typeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ogEditButton)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ogEditButton)
                    .add(typeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(contrastNameTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layersDetailsScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                            .add(filePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(contrastNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(filePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layersDetailsScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ReloadFileButtonGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReloadFileButtonGroupActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_ReloadFileButtonGroupActionPerformed

    private void fileTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileTypeComboBoxActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ReloadFileButtonGroup;
    private javax.swing.JButton addLayersButton;
    private javax.swing.JComboBox backgroundComboBox;
    private javax.swing.JTextField contrastNameTextField;
    private javax.swing.JButton fileNameBrowseButton;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JTextField fileNameTextField;
    private javax.swing.JPanel filePanel;
    private javax.swing.JComboBox fileTypeComboBox;
    private javax.swing.JLabel fileTypeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane layersDetailsScrollPane;
    private javax.swing.JTextField numberOfLaysTextBox;
    private javax.swing.JButton ogEditButton;
    private javax.swing.JButton removeLayers;
    private javax.swing.JComboBox resolComboBox;
    private javax.swing.JComboBox scalefacComboBox;
    private javax.swing.JComboBox shiftsComboBox;
    private javax.swing.JComboBox typeComboBox;
    // End of variables declaration//GEN-END:variables

    
}
