/*
 * expParams.java
 *
 * Created on 07 January 2008, 15:53
 */

/**
 *
 * @author  avh45
 */
public class expParams extends javax.swing.JPanel {
    
    /** Creates new form expParams */
    public expParams() {
        initComponents();
    }
    
    public javax.swing.JScrollPane getBacksScrollPane() {
        return expParamsScrollabalePanel1.backsScrollPane;
    }
    
    public javax.swing.JScrollPane getScalesScrollPane() {
        return expParamsScrollabalePanel1.scalesScrollPane;
    }
    
    public javax.swing.JScrollPane getShiftsScrollPane() {
        return expParamsScrollabalePanel1.shiftsScrollPane;
    }    

    public javax.swing.JScrollPane getNbaScrollPane() {
        return expParamsScrollabalePanel1.nbairsScrollPane;
    } 
    
    public javax.swing.JScrollPane getNbsScrollPane() {
        return expParamsScrollabalePanel1.nbsubsScrollPane;
    } 
    
    public javax.swing.JButton getBacksAddButton() {
        return expParamsScrollabalePanel1.backsAddButton;
    }
    
    public javax.swing.JButton getBacksRemoveButton() {
        return expParamsScrollabalePanel1.backsRemoveButton;
    }    

    public javax.swing.JButton getScalesAddButton() {
        return expParamsScrollabalePanel1.scalesAddButton;
    }
    
    public javax.swing.JButton getScalesRemoveButton() {
        return expParamsScrollabalePanel1.scalesRemoveButton;
    } 
    
    public javax.swing.JButton getShiftsAddButton() {
        return expParamsScrollabalePanel1.shiftsAddButton;
    }
    
    public javax.swing.JButton getShiftsRemoveButton() {
        return expParamsScrollabalePanel1.shiftsRemoveButton;
    }     

    public javax.swing.JButton getNbaAddButton() {
        return expParamsScrollabalePanel1.nbaAddButton;
    }
    
    public javax.swing.JButton getNbaRemoveButton() {
        return expParamsScrollabalePanel1.nbaRemoveButton;
    } 

    public javax.swing.JButton getNbsAddButton() {
        return expParamsScrollabalePanel1.nbsAddButton;
    }
    
    public javax.swing.JButton getNbsRemoveButton() {
        return expParamsScrollabalePanel1.nbsRemoveButton;
    }
    
    public javax.swing.JButton getResolAddButton() {
        return expParamsScrollabalePanel1.resolAddButton;
    }
    
    public javax.swing.JButton getResolRemoveButton() {
        return expParamsScrollabalePanel1.resolRemoveButton;
    }
    
    public javax.swing.JScrollPane getResolutionScrollPane() {
        return expParamsScrollabalePanel1.resolutionScrollPane;
    }  
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        expParamsScrollabalePanel1 = new expParamsScrollabalePanel();

        jScrollPane1.setViewportView(expParamsScrollabalePanel1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private expParamsScrollabalePanel expParamsScrollabalePanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
