/*
 * mainEditGuiFrame.java
 *
 * Created on 04 January 2008, 10:13
 */
import javax.swing.JTabbedPane;
import javax.swing.JButton;
import java.awt.BorderLayout;
import java.awt.Component;
import javax.swing.JInternalFrame;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Container;
import org.jdesktop.jxlayer.JXLayer;
import org.jdesktop.jxlayer.plaf.ext.LockableUI;
//import org.jdesktop.jxlayer.plaf.effect.BufferedImageOpEffect;
//import com.jhlabs.image.BlurFilter;
import java.lang.String;
/**
 *
 * @author  Arwel
 */
public class mainEditGuiFrame extends JInternalFrame {
    
    private JXLayer<JComponent> layer;
    private LockableUI blurUI = new LockableUI();
    
    /** Creates new form mainEditGuiFrame */
    public mainEditGuiFrame() {
        initComponents();
        JComponent view = (JComponent) this.getContentPane();  
        layer = new JXLayer(view, blurUI);
        blurUI.setLocked(false);
        layer.setUI(blurUI);
        this.setContentPane((layer));
    }
    
    public JTabbedPane getPanel() {
        return jTabbedPane1;
    }

    public javax.swing.JButton getMainCancelButton() {
        return mainCancelButton;
    }

    public javax.swing.JButton getMainOKButton() {
        return mainOKButton;
    }
    
    public void setLocked() {
        blurUI.setLocked(true);
        repaint();
    }

    public void setUnlocked() {
        blurUI.setLocked(false);
        repaint();
    }
    
    public LockableUI getLockingPane() {
        return blurUI;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        mainOKButton = new javax.swing.JButton();
        mainCancelButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setMaximizable(true);
        setResizable(true);
        mainOKButton.setText("OK");

        mainCancelButton.setText("Cancel");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(mainOKButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(5, 5, 5)
                        .add(mainCancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(mainCancelButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(mainOKButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTabbedPane jTabbedPane1;
    javax.swing.JButton mainCancelButton;
    javax.swing.JButton mainOKButton;
    // End of variables declaration//GEN-END:variables
    
}
