/*
 * slidersWindow.java
 *
 * Created on 01 February 2008, 12:44
 */

/**
 *
 * @author  avh45
 */
public class slidersWindow extends javax.swing.JInternalFrame {
    
    /** Creates new form slidersWindow */
    public slidersWindow() {
        initComponents();
    }

    public javax.swing.JButton getJSliderCancelButton() {
        return jSliderCancelButton;
    }

    public javax.swing.JButton getJSliderOkButton() {
        return jSliderOkButton;
    }

    public javax.swing.JScrollPane getJSliderScrollPane() {
        return jSliderScrollPane;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSliderCancelButton = new javax.swing.JButton();
        jSliderOkButton = new javax.swing.JButton();
        jSliderScrollPane = new javax.swing.JScrollPane();

        setMaximizable(true);
        setResizable(true);
        setTitle("Sliders");
        jSliderCancelButton.setText("Cancel");

        jSliderOkButton.setText("OK");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jSliderOkButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSliderCancelButton))
                    .add(jSliderScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jSliderScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jSliderCancelButton)
                    .add(jSliderOkButton))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jSliderCancelButton;
    private javax.swing.JButton jSliderOkButton;
    private javax.swing.JScrollPane jSliderScrollPane;
    // End of variables declaration//GEN-END:variables
    
}
