/*
 * openGenieWindow.java
 *
 * Created on 28 August 2008, 12:33
 */
import java.util.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.border.*;
import java.io.Serializable;

/**
 *
 * @author  avh45
 */
public class openGenieWindow extends javax.swing.JInternalFrame implements Serializable {
    
    /** Creates new form openGenieWindow */
    public openGenieWindow() {
        initComponents();

    }

    public javax.swing.JButton getCancelButton() {
        return cancelButton;
    }

    public javax.swing.JComboBox getDataTypeComboBox() {
        return dataTypeComboBox;
    }

    public javax.swing.JComboBox getInstrumentComboBox() {
        return instrumentComboBox;
    }

    public javax.swing.JSpinner getNumberOfAnglesSpinner() {
        return numberOfAnglesSpinner;
    }

    public javax.swing.JButton getOkButton() {
        return okButton;
    }

    public javax.swing.JScrollPane getOpenGenieTableScrollPane() {
        return openGenieTableScrollPane;
    }

    public javax.swing.JLabel getTransmissionRunLabel() {
        return transmissionRunLabel;
    }

    public javax.swing.JTextField getTransmissionRunTextField() {
        return transmissionRunTextField;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel2 = new javax.swing.JLabel();
        dataTypeComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        numberOfAnglesSpinner = new javax.swing.JSpinner();
        openGenieTableScrollPane = new javax.swing.JScrollPane();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        transmissionRunTextField = new javax.swing.JTextField();
        transmissionRunLabel = new javax.swing.JLabel();
        instrumentComboBox = new javax.swing.JComboBox();

        setMaximizable(true);
        setResizable(true);
        setTitle("OpenGenie ");
        jLabel2.setText("Data Type :");

        dataTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solid / Liquid", "Air / Liquid (or solid)" }));

        jLabel3.setText("Number of Angles : ");

        cancelButton.setText("Cancel");

        okButton.setText("Ok");

        jLabel1.setText("Instrument:");

        transmissionRunTextField.setText("80158");

        transmissionRunLabel.setText("Transmission Run:");

        instrumentComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Surf", "Crisp" }));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(openGenieTableScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(dataTypeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(numberOfAnglesSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 287, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(transmissionRunLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(transmissionRunTextField)
                            .add(instrumentComboBox, 0, 102, Short.MAX_VALUE))
                        .add(0, 0, 0))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(okButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(dataTypeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1)
                    .add(instrumentComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(numberOfAnglesSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(transmissionRunLabel)
                        .add(transmissionRunTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(openGenieTableScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelButton)
                    .add(okButton))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox dataTypeComboBox;
    private javax.swing.JComboBox instrumentComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner numberOfAnglesSpinner;
    private javax.swing.JButton okButton;
    private javax.swing.JScrollPane openGenieTableScrollPane;
    private javax.swing.JLabel transmissionRunLabel;
    private javax.swing.JTextField transmissionRunTextField;
    // End of variables declaration//GEN-END:variables
    
}


  
  



