/*
 * iframeMainControls.java
 *
 * Created on 29 July 2008, 12:30
 */

import javax.swing.ImageIcon;
import org.jdesktop.jxlayer.JXLayer;
import org.jdesktop.jxlayer.plaf.ext.LockableUI;
//import org.jdesktop.jxlayer.plaf.effect.BufferedImageOpEffect;
//import com.jhlabs.image.BlurFilter;
import javax.swing.JComponent;
import java.io.Serializable;

/**
 *
 * @author  avh45
 */
public class iframeMainControls extends javax.swing.JInternalFrame implements Serializable {
    
    private JXLayer<JComponent> layer;
    private LockableUI blurUI = new LockableUI();
    //public ImageIcon hourglassBusy;
    
    /** Creates new form iframeMainControls */
    public iframeMainControls(ImageIcon hourGlassGif, ImageIcon stopIcon, ImageIcon readyIcon) {
        initComponents();
        mainControlsPanel1.hourglass = hourGlassGif;
        mainControlsPanel1.stopIcon = stopIcon;
        mainControlsPanel1.readyIcon = readyIcon;
        JComponent view = (JComponent) this.getContentPane();  
        layer = new JXLayer(view, blurUI);
        blurUI.setLocked(false);
        layer.setUI(blurUI);
        this.setContentPane((layer));
    }
    
        public void setLocked() {
        blurUI.setLocked(true);
        repaint();
    }

    public void setUnlocked() {
        blurUI.setLocked(false);
        repaint();
    }
    
    public LockableUI getLockingPane() {
        return blurUI;
    }

    public mainControlsPanel getMainControlsPanel1() {
        return mainControlsPanel1;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        mainControlsPanel1 = new mainControlsPanel();

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainControlsPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainControlsPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private mainControlsPanel mainControlsPanel1;
    // End of variables declaration//GEN-END:variables
    
}
