/*
 * mainControlsPanel.java
 *
 * Created on 30 May 2008, 15:58
 */
import java.io.Serializable;
/**
 *
 * @author  avh45
 */

import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.SwingConstants;
//import java.io.File;


public class mainControlsPanel extends javax.swing.JPanel implements Serializable{
    
    public int stopFlag;
    public ImageIcon hourglass;
    public ImageIcon stopIcon;
    public ImageIcon readyIcon;
    
    /** Creates new form mainControlsPanel */
    public mainControlsPanel() {
        initComponents();
        setStopFlag(0);
    }

    public int getStopFlag() {
        return stopFlag;
    }

    public void setStopFlag(int stopFlag) {
        this.stopFlag = stopFlag;
    }

    public javax.swing.JLabel getAlgBox() {
        return algBox;
    }

    public javax.swing.JTextField getMaxIterVal() {
        return maxIterVal;
    }

    public javax.swing.JButton getStopFitButton() {
        return stopFitButton;
    }

    public javax.swing.JLabel getValChiSq() {
        return valChiSq;
    }

    public javax.swing.JButton getRunFitButton() {
        return runFitButton;
    }
    
    public void setImageIcon(ImageIcon icon) {
        hourglass = icon;
    }

    public javax.swing.JLabel getIconContainer() {
        return iconContainer;
    }
    
    public void changeIconToHourglass() {
        iconContainer.setIcon(hourglass);
        iconContainer.setHorizontalTextPosition(SwingConstants.CENTER);
        iconContainer.validate();
    }
    
    public void changeIconToStop() {
        iconContainer.setIcon(stopIcon);
        iconContainer.setHorizontalTextPosition(SwingConstants.CENTER);
        iconContainer.validate();
    }
    
    public void changeIconToReady() {
        iconContainer.setIcon(readyIcon);
        iconContainer.setHorizontalTextPosition(SwingConstants.CENTER);
        iconContainer.validate();
    }

    public javax.swing.JLabel getStatusBox() {
        return statusBox;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        iconContainer = new javax.swing.JLabel();
        runFitButton = new javax.swing.JButton();
        stopFitButton = new javax.swing.JButton();
        statusBox = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        algBox = new javax.swing.JLabel();
        valChiSq = new javax.swing.JLabel();
        maxIterVal = new javax.swing.JTextField();

        iconContainer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        runFitButton.setText("Run Fit");
        runFitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runFitButtonActionPerformed(evt);
            }
        });

        stopFitButton.setText("Stop Fit");
        stopFitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopFitButtonActionPerformed(evt);
            }
        });

        statusBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusBox.setText("Ready");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Algorithm is :");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Chi Sq is :");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Max Iterations :");

        algBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        algBox.setText("Simplex");
        algBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        valChiSq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valChiSq.setText("0.0");
        valChiSq.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        maxIterVal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maxIterVal.setText("100");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(runFitButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(72, 72, 72)
                        .add(stopFitButton))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, algBox, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .add(valChiSq, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .add(maxIterVal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                .add(16, 16, 16)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(iconContainer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .add(statusBox, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(algBox)
                    .add(statusBox))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(15, 15, 15)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel4)
                            .add(valChiSq))
                        .add(15, 15, 15)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel5)
                            .add(maxIterVal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(runFitButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(stopFitButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(iconContainer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void stopFitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopFitButtonActionPerformed
        changeIconToStop();
        setStopFlag(1);
    }//GEN-LAST:event_stopFitButtonActionPerformed

    private void runFitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runFitButtonActionPerformed
        //changeIconToHourglass();
    }//GEN-LAST:event_runFitButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel algBox;
    private javax.swing.JLabel iconContainer;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField maxIterVal;
    private javax.swing.JButton runFitButton;
    private javax.swing.JLabel statusBox;
    private javax.swing.JButton stopFitButton;
    private javax.swing.JLabel valChiSq;
    // End of variables declaration//GEN-END:variables
    
}
